"""empty message

Revision ID: 2d3d430f457b
Revises: c769b423e59b
Create Date: 2018-11-05 14:35:45.320632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3d430f457b'
down_revision = 'c769b423e59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    # ### end Alembic commands ###
