"""empty message

Revision ID: 5f9a2f65a711
Revises: 2d3d430f457b
Create Date: 2018-11-05 15:17:31.109924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9a2f65a711'
down_revision = '2d3d430f457b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
