"""empty message

Revision ID: 65171f3f361b
Revises: 52d9f8e8ef03
Create Date: 2018-11-30 20:33:34.865936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65171f3f361b'
down_revision = '52d9f8e8ef03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(length=32), nullable=False), schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash', schema='users')
    # ### end Alembic commands ###
