"""empty message

Revision ID: b57ddcf6be7c
Revises: fd9868ae1c7b
Create Date: 2018-12-17 23:37:18.240471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57ddcf6be7c'
down_revision = 'fd9868ae1c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False), schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin', schema='users')
    # ### end Alembic commands ###
