"""empty message

Revision ID: c769b423e59b
Revises: 2518d492b31b
Create Date: 2018-11-05 14:16:01.727265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c769b423e59b'
down_revision = '2518d492b31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
