"""empty message

Revision ID: ede6c8c1307e
Revises: b57ddcf6be7c
Create Date: 2018-12-30 17:26:56.067801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede6c8c1307e'
down_revision = 'b57ddcf6be7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expiration', sa.Date(), nullable=True), schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expiration', schema='users')
    # ### end Alembic commands ###
