"""empty message

Revision ID: fd9868ae1c7b
Revises: f1e28ad30166
Create Date: 2018-12-17 22:13:30.650433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9868ae1c7b'
down_revision = 'f1e28ad30166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permissions', ['code'], schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', schema='users', type_='unique')
    # ### end Alembic commands ###
